name: Build Documentation

on:
  push:
    branches:
      - main
      - doc-builder*
    paths:
      - docs/**
      - examples/**/*.md
      - examples/**/*.ipynb
      - .github/workflows/doc-build.yml

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: Microsoft-Azure
      package_name: microsoft-azure
      additional_args: --not_python_module
      pre_command: cd Microsoft-Azure && make docs
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
