name: Build PR Documentation

on:
  pull_request:
    paths:
      - docs/**
      - examples/**/*.md
      - examples/**/*.ipynb
      - .github/workflows/doc-pr-build.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_pr_documentation.yml@main
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.number }}
      package: Microsoft-Azure
      package_name: microsoft-azure
      additional_args: --not_python_module
      pre_command: cd Microsoft-Azure && make docs
